name: 'JFrog Maven Deployer - Auth Token'
description: >
  Uploads a JAR and its POM to Artifactory using only JFrog CLI.
  JFrog CLI fetches short-lived OIDC credentials – no static tokens.

inputs:
  jar-path:         { description: 'Absolute path to the JAR', required: true }
  pom-path:         { description: 'Absolute path to the POM', required: true }
  jfrog-url:        { description: 'https://acme.jfrog.io', required: true }
  jfrog-repo-path: {description: 'Path of the Jfrog Repo that the artifact will be upload', required: true}
  jf-access-token: { description: 'JFrog Access Token', required: true }

runs:
  using: composite
  steps:

    - name: Validate artefacts exist
      shell: bash
      run: |
        for f in "${{ inputs.jar-path }}" "${{ inputs.pom-path }}"; do
          [[ -f "$f" ]] || { echo "::error::$f not found"; exit 1; }
        done

    - name: Setup JFrog CLI 
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ inputs.jfrog-url }}
        JF_ACCESS_TOKEN: ${{ inputs.jf-access-token }}


    - name: Upload artefacts with JFrog CLI
      shell: bash
      run: |
        jf rt upload "${{ inputs.pom-path }}" \
          "${{ inputs.jfrog-repo-path }}/" --flat=true
        jf rt upload "${{ inputs.jar-path }}" \
          "${{ inputs.jfrog-repo-path }}" --flat=true
