name: Test JFrog Maven Deploy (CLI-only)

on: [push, workflow_dispatch]

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}

    permissions:
      id-token: write   # GitHub → JWT → JFrog OIDC
      contents: read

    strategy:
      fail-fast: false
      matrix:
        env: [development, qa]

    steps:
      - uses: actions/checkout@v4

      - name: Generate dummy artefacts
        id: gen
        shell: bash
        run: |
          ts=$(date +%s)
          ver="1.0-${{ matrix.env }}.$ts"

          pom="dummy-artifact-$ver.pom"
          jar="dummy-artifact-$ver.jar"

          cat >"$pom" <<EOF
          <project>
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.test.local</groupId>
            <artifactId>dummy-artifact</artifactId>
            <version>$ver</version>
            <packaging>jar</packaging>
          </project>
          EOF

          printf 'Test content – %s\n' "$ts" >content.txt
          zip "$jar" content.txt && rm content.txt

          echo "pom=$pom" >>"$GITHUB_OUTPUT"
          echo "jar=$jar" >>"$GITHUB_OUTPUT"

      - name: Deploy via JFrog CLI (OIDC)
        uses: ./.github/actions/jfrog-maven-deployer
        with:
          pom-path:           ${{ steps.gen.outputs.pom }}
          jar-path:           ${{ steps.gen.outputs.jar }}
          repository-id:      ${{ vars.REPO_ID }}   # ej. libs-snapshot-local
          jfrog-url:          ${{ vars.JF_URL }}    # ej. https://acme.jfrog.io
          oidc-provider-name: github
          oidc-audience:      my-aud
